import { Puzzle } from '../types';

export const PUZZLES: Puzzle[] = [
  { id: 1, image: 'images/Rebus 1.1.png', answer: 'For once in my life' },
  { id: 2, image: 'images/Rebus 1.2.png', answer: 'Forget it' },
  { id: 3, image: 'images/Rebus 1.3.png', answer: 'Try to understand' },
  { id: 4, image: 'images/Rebus 1.4.png', answer: 'Travel overseas' },
  { id: 5, image: 'images/Rebus 1.5.png', answer: 'Breakfast' },
  { id: 6, image: 'images/Rebus 1.6.png', answer: 'Downtown' },
  { id: 7, image: 'images/Rebus 1.7.png', answer: 'Eyeshadow' },
  { id: 8, image: 'images/Rebus 1.8.png', answer: 'Stepfather' },
  { id: 9, image: 'images/Rebus 1.9.png', answer: 'Once upon a time' },
  { id: 10, image: 'images/Rebus 1.10.png', answer: 'Potatoes' },
  { id: 11, image: 'images/Rebus 1.11.png', answer: '3D movie' },
  { id: 12, image: 'images/Rebus 1.12.png', answer: 'Top secret' },
  { id: 13, image: 'images/Rebus2.1.png', answer: 'Trip around the world' },
  { id: 14, image: 'images/Rebus2.2.png', answer: 'Lemonade' },
  { id: 15, image: 'images/Rebus2.3.png', answer: 'Long legs' },
  { id: 16, image: 'images/Rebus2.4.png', answer: 'advice' },
  { id: 17, image: 'images/Rebus2.5.png', answer: 'Spaceman' },
  { id: 18, image: 'images/Rebus2.6.png', answer: 'Big bad wolf' },
  { id: 19, image: 'images/Rebus2.7.png', answer: 'Many thanks' },
  { id: 20, image: 'images/Rebus2.8.png', answer: 'Download' },
  { id: 21, image: 'images/Rebus2.9.png', answer: 'No idea' },
  { id: 22, image: 'images/Rebus2.10.png', answer: 'Comfortable' },
  { id: 23, image: 'images/Rebus2.11.png', answer: 'Forty years' },
  { id: 24, image: 'images/Rebus2.12.png', answer: 'Excuse me' },
  { id: 25, image: 'images/Rebus3.1.png', answer: 'Forehead' },
  { id: 26, image: 'images/Rebus3.2.png', answer: 'Good looking' },
  { id: 27, image: 'images/Rebus3.3.png', answer: 'Waterfall' },
  { id: 28, image: 'images/Rebus3.4.png', answer: 'Wake up' },
  { id: 29, image: 'images/Rebus3.5.png', answer: 'Tuna fish' },
  { id: 30, image: 'images/Rebus3.6.png', answer: 'Foreign language' },
  { id: 31, image: 'images/Rebus3.7.png', answer: 'Seahorse' },
  { id: 32, image: 'images/Rebus3.8.png', answer: 'Middle-aged' },
  { id: 33, image: 'images/Rebus3.9.png', answer: 'Broken heart' },
  { id: 34, image: 'images/Rebus3.10.png', answer: 'Seesaw' },
  { id: 35, image: 'images/Rebus3.11.png', answer: 'Miss you' },
  { id: 36, image: 'images/Rebus3.12.png', answer: 'Teabag' },
  { id: 37, image: 'images/Rebus4.1.png', answer: 'Four-wheel drive' },
  { id: 38, image: 'images/Rebus4.2.png', answer: 'Apple pie' },
  { id: 39, image: 'images/Rebus4.3.png', answer: 'Up to you' },
  { id: 40, image: 'images/Rebus4.4.png', answer: 'Robin Hood' },
  { id: 41, image: 'images/Rebus4.5.png', answer: 'Design' },
  { id: 42, image: 'images/Rebus4.6.png', answer: 'Engineer' },
  { id: 43, image: 'images/Rebus4.7.png', answer: 'Vegetables' },
  { id: 44, image: 'images/Rebus4.8.png', answer: 'Afternoon tea' },
  { id: 45, image: 'images/Rebus4.9.png', answer: 'Camping overnight' },
  { id: 46, image: 'images/Rebus4.10.png', answer: 'Time to go' },
  { id: 47, image: 'images/Rebus4.11.png', answer: 'Long time no see' },
  { id: 48, image: 'images/Rebus4.12.png', answer: 'Polite' },
  { id: 49, image: 'images/Rebus5.1.png', answer: 'Fishing hook' },
  { id: 50, image: 'images/Rebus5.2.png', answer: 'Farm animal' },
  { id: 51, image: 'images/Rebus5.3.png', answer: 'Touchdown' },
  { id: 52, image: 'images/Rebus5.4.png', answer: 'Honeybee' },
  { id: 53, image: 'images/Rebus5.5.png', answer: 'Cornerstone' },
  { id: 54, image: 'images/Rebus5.6.png', answer: 'Love at first sight' },
  { id: 55, image: 'images/Rebus5.7.png', answer: 'Freeze over' },
  { id: 56, image: 'images/Rebus5.8.png', answer: 'Caveman' },
  { id: 57, image: 'images/Rebus5.9.png', answer: 'Catwalk' },
  { id: 58, image: 'images/Rebus5.10.png', answer: 'Hiking in the woods' },
  { id: 59, image: 'images/Rebus5.11.png', answer: 'Sandbox' },
  { id: 60, image: 'images/Rebus5.12.png', answer: 'Lovebirds' },
  { id: 61, image: 'images/Rebus6.1.png', answer: 'Crossbow' },
  { id: 62, image: 'images/Rebus6.2.png', answer: 'Eggs over easy' },
  { id: 63, image: 'images/Rebus6.3.png', answer: 'Coffee break' },
  { id: 64, image: 'images/Rebus6.4.png', answer: 'Multiple choice' },
  { id: 65, image: 'images/Rebus6.5.png', answer: 'Come into season' },
  { id: 66, image: 'images/Rebus6.6.png', answer: 'I’ll get over it' },
  { id: 67, image: 'images/Rebus6.7.png', answer: 'Raincheck' },
  { id: 68, image: 'images/Rebus6.8.png', answer: 'I’m bigger than you' },
  { id: 69, image: 'images/Rebus6.9.png', answer: 'Illegal' },
  { id: 70, image: 'images/Rebus6.10.png', answer: 'Double agent' },
  { id: 71, image: 'images/Rebus6.11.png', answer: 'Rock n roll' },
  { id: 72, image: 'images/Rebus6.12.png', answer: 'Good afternoon' },
  { id: 73, image: 'images/Rebus7.1.png', answer: 'Look me in the eye' },
  { id: 74, image: 'images/Rebus7.2.png', answer: 'Electric blanket' },
  { id: 75, image: 'images/Rebus7.3.png', answer: 'Banknote' },
  { id: 76, image: 'images/Rebus7.4.png', answer: 'One foot in the door' },
  { id: 77, image: 'images/Rebus7.5.png', answer: 'Bookcase' },
  { id: 78, image: 'images/Rebus7.6.png', answer: 'Five kilograms overweight' },
  { id: 79, image: 'images/Rebus7.7.png', answer: 'Highway' },
  { id: 80, image: 'images/Rebus7.8.png', answer: 'Way to go' },
  { id: 81, image: 'images/Rebus7.9.png', answer: 'Toothpick' },
  { id: 82, image: 'images/Rebus7.10.png', answer: 'Underdogs' },
  { id: 83, image: 'images/Rebus7.11.png', answer: 'Heartbeat' },
  { id: 84, image: 'images/Rebus7.12.png', answer: 'Light rain' },
  { id: 85, image: 'images/Rebus8.1.png', answer: 'Sunroof' },
  { id: 86, image: 'images/Rebus8.2.png', answer: 'X-ray' },
  { id: 87, image: 'images/Rebus8.3.png', answer: 'Doghouse' },
  { id: 88, image: 'images/Rebus8.4.png', answer: 'Excuse me' },
  { id: 89, image: 'images/Rebus8.5.png', answer: 'French fry' },
  { id: 90, image: 'images/Rebus8.6.png', answer: 'Pardon me' },
  { id: 91, image: 'images/Rebus8.7.png', answer: 'Mousetrap' },
  { id: 92, image: 'images/Rebus8.8.png', answer: 'Turnip' },
  { id: 93, image: 'images/Rebus8.9.png', answer: 'Phone numbers' },
  { id: 94, image: 'images/Rebus8.10.png', answer: 'Uproar' },
  { id: 95, image: 'images/Rebus8.11.png', answer: 'Thunderstorm' },
  { id: 96, image: 'images/Rebus8.12.png', answer: 'Weekend' },
  { id: 97, image: 'images/Rebus9.1.png', answer: 'Cuba' },
  { id: 98, image: 'images/Rebus9.2.png', answer: 'Eiffel Tower' },
  { id: 99, image: 'images/Rebus9.3.png', answer: 'Supermarket' },
  { id: 100, image: 'images/Rebus9.4.png', answer: 'Laundromat' },
  { id: 101, image: 'images/Rebus9.5.png', answer: 'Angkor Wat' },
  { id: 102, image: 'images/Rebus9.6.png', answer: 'Tunnel' },
  { id: 103, image: 'images/Rebus9.7.png', answer: 'Iran' },
  { id: 104, image: 'images/Rebus9.8.png', answer: 'Boxing ring' },
  { id: 105, image: 'images/Rebus9.9.png', answer: 'Mount Rushmore' },
  { id: 106, image: 'images/Rebus9.10.png', answer: 'Finland' },
  { id: 107, image: 'images/Rebus9.11.png', answer: 'Micronesia' },
  { id: 108, image: 'images/Rebus9.12.png', answer: 'Hairdresser' },
  { id: 109, image: 'images/Rebus10.1.png', answer: 'Microscope' },
  { id: 110, image: 'images/Rebus10.2.png', answer: 'One night stand' },
  { id: 111, image: 'images/Rebus10.3.png', answer: 'Eye sockets' },
  { id: 112, image: 'images/Rebus10.4.png', answer: 'Houseplant' },
  { id: 113, image: 'images/Rebus10.5.png', answer: 'Neighbourhood' },
  { id: 114, image: 'images/Rebus10.6.png', answer: 'Failure' },
  { id: 115, image: 'images/Rebus10.7.png', answer: 'Headquarters' },
  { id: 116, image: 'images/Rebus10.8.png', answer: 'Blanket' },
  { id: 117, image: 'images/Rebus10.9.png', answer: 'Cut corners' },
  { id: 118, image: 'images/Rebus10.10.png', answer: 'Cocktail' },
  { id: 119, image: 'images/Rebus10.11.png', answer: 'Tennis shoes' },
  { id: 120, image: 'images/Rebus10.12.png', answer: 'Summary' },
  { id: 121, image: 'images/Rebus11.1.png', answer: 'Teacup' },
  { id: 122, image: 'images/Rebus11.2.png', answer: 'Fly screen' },
  { id: 123, image: 'images/Rebus11.3.png', answer: 'Metaphor' },
  { id: 124, image: 'images/Rebus11.4.png', answer: 'Leftover' },
  { id: 125, image: 'images/Rebus11.5.png', answer: 'Bad influence' },
  { id: 126, image: 'images/Rebus11.6.png', answer: 'Backhand' },
  { id: 127, image: 'images/Rebus11.7.png', answer: 'Sunken' },
  { id: 128, image: 'images/Rebus11.8.png', answer: 'Wise guy' },
  { id: 129, image: 'images/Rebus11.9.png', answer: 'Stay indoors' },
  { id: 130, image: 'images/Rebus11.10.png', answer: 'Crystallise' },
  { id: 131, image: 'images/Rebus11.11.png', answer: 'Elbow' },
  { id: 132, image: 'images/Rebus11.12.png', answer: 'New Zealand' },
  { id: 133, image: 'images/Rebus12.1.png', answer: 'Unbroken' },
  { id: 134, image: 'images/Rebus12.2.png', answer: 'Highchair' },
  { id: 135, image: 'images/Rebus12.3.png', answer: 'Foul language' },
  { id: 136, image: 'images/Rebus12.4.png', answer: 'Summer' },
  { id: 137, image: 'images/Rebus12.5.png', answer: 'Cattle' },
  { id: 138, image: 'images/Rebus12.6.png', answer: 'Four seasons' },
  { id: 139, image: 'images/Rebus12.7.png', answer: 'Mutate' },
  { id: 140, image: 'images/Rebus12.8.png', answer: 'Coloring' },
  { id: 141, image: 'images/Rebus12.9.png', answer: 'Indian food' },
  { id: 142, image: 'images/Rebus12.10.png', answer: 'The underdog' },
  { id: 143, image: 'images/Rebus12.11.png', answer: 'The birds and the bees' },
  { id: 144, image: 'images/Rebus12.12.png', answer: 'Tripod' },
  { id: 145, image: 'images/Rebus13.1.png', answer: 'Pecan nuts' },
  { id: 146, image: 'images/Rebus13.2.png', answer: 'Seasoning' },
  { id: 147, image: 'images/Rebus13.3.png', answer: 'Karaoke' },
  { id: 148, image: 'images/Rebus13.4.png', answer: 'Easel' },
  { id: 149, image: 'images/Rebus13.5.png', answer: 'Horsefly' },
  { id: 150, image: 'images/Rebus13.6.png', answer: 'Shotgun' },
  { id: 151, image: 'images/Rebus13.7.png', answer: 'Discount' },
  { id: 152, image: 'images/Rebus13.8.png', answer: 'Shoplift' },
  { id: 153, image: 'images/Rebus13.9.png', answer: 'Sidekicks' },
  { id: 154, image: 'images/Rebus13.10.png', answer: 'Gum tree' },
  { id: 155, image: 'images/Rebus13.11.png', answer: 'Keep your eyes on the ball' },
  { id: 156, image: 'images/Rebus13.12.png', answer: 'Fortunate' },
  { id: 157, image: 'images/Rebus14.1.png', answer: 'Shake a leg' },
  { id: 158, image: 'images/Rebus14.2.png', answer: 'Hot under the collar' },
  { id: 159, image: 'images/Rebus14.3.png', answer: 'Sweet tooth' },
  { id: 160, image: 'images/Rebus14.4.png', answer: 'An old hand' },
  { id: 161, image: 'images/Rebus14.5.png', answer: 'A bone to pick' },
  { id: 162, image: 'images/Rebus14.6.png', answer: 'To be in a pickle' },
  { id: 163, image: 'images/Rebus14.7.png', answer: 'Fingers crossed' },
  { id: 164, image: 'images/Rebus14.8.png', answer: 'See eye to eye' },
  { id: 165, image: 'images/Rebus14.9.png', answer: 'Backburner' },
  { id: 166, image: 'images/Rebus14.10.png', answer: 'Sixth sense' },
  { id: 167, image: 'images/Rebus14.11.png', answer: 'Breaking point' },
  { id: 168, image: 'images/Rebus14.12.png', answer: 'On second thought' },
  { id: 169, image: 'images/Rebus15.1.png', answer: 'Word of mouth' },
  { id: 170, image: 'images/Rebus15.2.png', answer: 'A chain of events' },
  { id: 171, image: 'images/Rebus15.3.png', answer: 'Sleep on it' },
  { id: 172, image: 'images/Rebus15.4.png', answer: 'Jockey for position' },
  { id: 173, image: 'images/Rebus15.5.png', answer: 'Hit the hay' },
  { id: 174, image: 'images/Rebus15.6.png', answer: 'All in a days work' },
  { id: 175, image: 'images/Rebus15.7.png', answer: 'Door to door' },
  { id: 176, image: 'images/Rebus15.8.png', answer: 'Draw blood' },
  { id: 177, image: 'images/Rebus15.9.png', answer: 'A flash in the pan' },
  { id: 178, image: 'images/Rebus15.10.png', answer: 'A barrel of laughs' },
  { id: 179, image: 'images/Rebus15.11.png', answer: 'Two ships passing in the night' },
  { id: 180, image: 'images/Rebus15.12.png', answer: 'Safe and sound' },
  { id: 181, image: 'images/Rebus16.1.png', answer: 'Holy man' },
  { id: 182, image: 'images/Rebus16.2.png', answer: 'Be on time' },
  { id: 183, image: 'images/Rebus16.3.png', answer: 'Trillion' },
  { id: 184, image: 'images/Rebus16.4.png', answer: 'Peasants' },
  { id: 185, image: 'images/Rebus16.5.png', answer: 'Backpedal' },
  { id: 186, image: 'images/Rebus16.6.png', answer: 'Forecast' },
  { id: 187, image: 'images/Rebus16.7.png', answer: 'Noodles' },
  { id: 188, image: 'images/Rebus16.8.png', answer: 'Surface' },
  { id: 189, image: 'images/Rebus16.9.png', answer: 'Launder money' },
  { id: 190, image: 'images/Rebus16.10.png', answer: 'Peace on earth' },
  { id: 191, image: 'images/Rebus16.11.png', answer: 'Hand in hand' },
  { id: 192, image: 'images/Rebus16.12.png', answer: 'Beetroot' },
  { id: 193, image: 'images/Rebus17.1.png', answer: 'India' },
  { id: 194, image: 'images/Rebus17.2.png', answer: 'Lunatics' },
  { id: 195, image: 'images/Rebus17.3.png', answer: 'Mayonnaise' },
  { id: 196, image: 'images/Rebus17.4.png', answer: 'Elbows' },
  { id: 197, image: 'images/Rebus17.5.png', answer: 'Administrator' },
  { id: 198, image: 'images/Rebus17.6.png', answer: 'Entree' },
  { id: 199, image: 'images/Rebus17.7.png', answer: 'Leftovers' },
  { id: 200, image: 'images/Rebus17.8.png', answer: 'Domino' },
  { id: 201, image: 'images/Rebus17.9.png', answer: 'Rampant' },
  { id: 202, image: 'images/Rebus17.10.png', answer: 'Cold beer' },
  { id: 203, image: 'images/Rebus17.11.png', answer: 'Canine' },
  { id: 204, image: 'images/Rebus17.12.png', answer: 'July' },
];
